{{- if .Values.metadata }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}-metadata
  {{- include "common.metadata" ( dict "root" $ "service" $.Values ) | nindent 2 }}
data:
  CHART_NAME: {{ .Chart.Name }}
  RELEASE_NAME: {{ .Release.Name }}
  RELEASE_NAMESPACE: {{ .Release.Namespace }}
{{- end }}
