{{- if .Values.dockerregistry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}-dockerregistry
  {{- include "common.metadata" ( dict "root" . "service" .Values ) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "secrets.dockerregistry" . | b64enc }}
{{- end }}
