{{- if .Values.dockerregistry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}-dockerregistry
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
{{- with $.Values.annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "secrets.dockerregistry" . | b64enc }}
{{- end }}
