{{- if .Values.external }}
{{- with .Values.externalSecrets }}
{{- if ( or .data .dataFrom ) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values ) | nindent 2 }}
spec:
  {{- with .refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with .secretStoreRef }}
  secretStoreRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  target:
    name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}
  {{- with .dataFrom }}
  dataFrom: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .data }}
  data: {{- include "common.dictToList" ( dict "keyName" "secretKey" "contents" . ) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
