{{- if .Values.external }}
{{- if .Values.dockerregistry }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}-dockerregistry
  {{- include "common.metadata" ( dict "root" $ "service" $.Values ) | nindent 2 }}
spec:
  {{- with $.Values.dockerregistryRefreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $.Values.dockerregistrySecretStoreRef }}
  secretStoreRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  target:
    name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}-dockerregistry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{- include "application.secrets.externaldockerregistry" .Values.dockerregistry | nindent 10 }}
  data:
  {{- range $registryName, $conf := .Values.dockerregistry }}
  {{- with $conf.externalUsername }}
    - secretKey: {{ $registryName }}_username
      remoteRef:
        key: {{ $conf.externalUsername }}
  {{- end }}
  {{- with $conf.externalPassword }}
    - secretKey: {{ $registryName }}_password
      remoteRef:
        key: {{ $conf.externalPassword }}
  {{- end }}
  {{- with $conf.externalEmail }}
    - secretKey: {{ $registryName }}_email
      remoteRef:
        key: {{ $conf.externalEmail }}
  {{- end }}
  {{- with $conf.externalUrl }}
    - secretKey: {{ $registryName }}_url
      remoteRef:
        key: {{ $conf.externalUrl }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
