{{- with .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values ) | nindent 4 }}
type: generic
data:
{{- range $key, $value := . }}
{{- if eq ( default "value" $value.type ) "value" }}
  {{ $key }}: {{ $value.value | b64enc }}
{{- else }}
{{- if eq $value.type "basicAuth" }}
  {{ $key }}: {{ ( printf "Basic %s" ( printf "%s:%s" $value.user $value.password ) | b64enc ) | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
